### ISSUE TITLE
Xmanager closes automatically while using on a MIUI device. 

### ISSUE THREAD

**Issue by slurrednblurred** [Team-xManager/xManager#367]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Redmi Note 9 Pro Max
- Android Version:  Android 12
- ROM Version:  stock
- xManager Version:  5.0
```

### 📝 Description

1.The Xmanager automatically closes on its own when I try to download any(amoled Or normal) spotify mod from it. 
2. The moment the ad starts playing, only after about 4-5 seconds of it, the app closes automatically. 
3.After reopening the app this this comes up : 

An error occurred : 
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.size()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.view.IWindowManager$Stub$Proxy.getSupportedDisplayHashAlgorithms(IWindowManager.java:6342)
	at android.view.displayhash.DisplayHashManager.getSupportedHashAlgorithms(DisplayHashManager.java:71)
	at com.google.android.gms.ads.eventattestation.internal.l.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:33)
	at com.google.android.gms.ads.nonagon.ad.j.e(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:247)
	at com.google.android.gms.ads.nonagon.ad.g.run(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.DisplayHashController.getDisplayHashAlgorithms(DisplayHashController.java:250)
	at com.android.server.wm.DisplayHashController.getSupportedHashAlgorithms(DisplayHashController.java:145)
	at com.android.server.wm.WindowManagerService.getSupportedDisplayHashAlgorithms(WindowManagerService.java:9218)
	at android.view.IWindowManager$Stub.onTransact(IWindowManager.java:2954)
	at com.android.server.wm.WindowManagerService.onTransact(WindowManagerService.java:1642)

...

### 📸 Screenshots

![Screenshot_2023-08-27-22-15-10-887_com xc3fff0e xmanager](https://github.com/Team-xManager/xManager/assets/90458001/71307a55-264e-40a0-beb6-58ea4db5d30e)

**Comment by pawelk1337** [comment]
Not a problem on xiaomi redme node 10 pro (sweet) 
On an reinstalled miui 14

**Comment by LackOfCreativiT** [comment]
also having this issue on a fresh galaxy s23

**Comment by leo-groome** [comment]
Same problem here i have a redmi note 12

**Comment by MrPancakes39** [comment]
My friend has a "Huawei Y7 2019" and doesn't have this issue after installing v5.1

**Comment by energ0n** [comment]
@slurrednblurred @LackOfCreativiT @leo-groome 

- are you still experiencing this issue on a clean install of xManager v5.4?
- does this happen on both wifi and mobile networks?
- can you confirm you have no "network-filtering" modifications on your device (firewalls, additional ad-block-like setups via DNS, VPN or root methods etc)? 
- does the crash still happen after disabling xManager ads in the xManager settings?

**Comment by LackOfCreativiT** [comment]
> @slurrednblurred @LackOfCreativiT @leo-groome
> 
> * are you still experiencing this issue on a clean install of xManager v5.4?
> * does this happen on both wifi and mobile networks?
> * can you confirm you have no "network-filtering" modifications on your device (firewalls, additional ad-block-like setups via DNS, VPN or root methods etc)?
> * does the crash still happen after disabling xManager ads in the xManager settings?

Given that I seem to have completely forgotten about this, no. Things seem to work as intended now.
