### ISSUE TITLE
Error when starting the app

### ISSUE THREAD

**Issue by yourfav-raphi** [Team-xManager/xManager#435]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy S10 
- Android Version:  12
- ROM Version:  stock
- xManager Version:  v5.2
```

### 📝 Description

1. Open app
2. Download Spotify 
3. Install sporify

Error:
`java.lang.IllegalArgumentException: Invalid payload item type
	at android.util.EventLog.writeEvent(Native Method)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10198)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10554)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

### 📸 Screenshots

![Screenshot_20231215_224922_xManager](https://github.com/Team-xManager/xManager/assets/130396673/2c98bcff-b7b8-4b11-b7bd-cc2bca21adc1)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by yourfav-raphi** [comment]
> GitHub issues for xManager should be used for the xManager app only.
> Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.
> 
> xManager Support Links:
> •Discord: https://discord.gg/dnpKn5Wufm
> •Reddit: https://www.reddit.com/r/xManagerApp/
> •Telegram (Support): https://t.me/xManagerSupport

But this is the xmanager app

**Comment by xC3FFF0E** [comment]
Alright. Have you tried the other version if the issue persists?

**Comment by yourfav-raphi** [comment]
> Alright. Have you tried the other version if the issue persists?

Yes it's still there
