### ISSUE TITLE
Unable to open on Android 14. Crash constantly 

### ISSUE THREAD

**Issue by lux5am** [Team-xManager/xManager#465]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  POCO X3
- Android Version:  14
- ROM Version:  crDroid 10.2
- xManager Version:  5.2 from github
```

### 📝 Description

1. Open
2. Showed startup animation then force close
3. What do?
...

Sometimes throwing this error after opening it multiple times
```log
java.lang.SecurityException: Unknown calling package name 'com.xc3fff0e.xmanager'.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3045)
	at android.os.Parcel.readException(Parcel.java:3028)
	at android.os.Parcel.readException(Parcel.java:2970)
	at com.google.android.gms.common.internal.zzab.getService(com.google.android.gms:play-services-basement@@17.6.0:9)
	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(com.google.android.gms:play-services-basement@@17.6.0:14)
	at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(com.google.android.gms:play-services-basement@@17.6.0:2)
	at com.google.android.gms.common.internal.zzg.zza(com.google.android.gms:play-services-basement@@17.6.0:1)
	at com.google.android.gms.common.internal.zza.zzd(Unknown Source:8)
	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@17.6.0:3)
	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@17.6.0:31)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

### 📸 Screenshots

Nothing
It just closed

**Comment by energ0n** [comment]
This issue is not specific to Android 14, but possibly the hardware or software of the device you are using.

I can confirm xManager v5.4 runs on A13/14/15 on various Google devices on both official stock/beta software. 

@lux5am are you still experiencing this issue after a clean install of xManager v5.4?

**Comment by lux5am** [comment]
No luck it's fine with my old phone running android 10

**Comment by exciar** [comment]
use Evo X instead? (same device)

**Comment by lux5am** [comment]
They have tele group. And they upload the apks in tele so I can just update them manually. Thanks anyway 👍🏻
