### ISSUE TITLE
Removing audio capture restriction

### ISSUE THREAD

**Issue by ArcPlayz** [Team-xManager/xManager#525]
### Description of the new feature / enhancement

AudioPlaybackCapture API doesn't work with Spotify (it's blocked explicitly by the app).
ReVanced provides way to remove that restriction, but modified app from xManager can't be patched successfully (because of some kind of problem with signing APK). Only patching original app works.
It would be nice to make that working with ReVanced or to remove the restriction directly in xManager.

Here's the error content from ReVanced patcher:
```
com.android.apksig.apk.ApkFormatException: Malformed ZIP entry: assets/org/apache/commons/math3/exception/util/LocalizedFormats_fr.properties
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:407)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:231)
        at app.revanced.library.ApkSigner$Signer.signApk(ApkSigner.kt:337)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:169)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:321)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: com.android.apksig.zip.ZipFormatException: Data Descriptor presence mismatch between Local File Header and Central Directory for entry assets/org/apache/commons/math3/exception/util/LocalizedFormats_fr.properties. LFH: true, CD: false
        at com.android.apksig.internal.zip.LocalFileRecord.getRecord(LocalFileRecord.java:180)
        at com.android.apksig.internal.zip.LocalFileRecord.getRecord(LocalFileRecord.java:127)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:404)
        ... 13 more
```

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport
